### ISSUE TITLE
还得是我子瑞哥

### ISSUE THREAD

**Issue by swpfY** [Feudalman/github-3vn5fs-hbcqgq#2]
哈哈哈，哈哈哈。哈哈哈

**Comment by Feudalman** [comment]
但是和咱们的秋山哥比还是差多了 o.0

**Comment by swpfY** [comment]
测试一下Issue功能来着

**Comment by swpfY** [comment]
不是仓库的协作者的话没法删除创建的issue

**Comment by Feudalman** [comment]
可以，记得咱们之前就试过这个

> 不是仓库的协作者的话没法删除创建的issue

**Comment by swpfY** [comment]
> 可以，记得咱们之前就试过这个
> 
> > 不是仓库的协作者的话没法删除创建的issue

我现在就删不了这个Issue
哈哈哈，哈哈哈

**Comment by Feudalman** [comment]
> > 可以，记得咱们之前就试过这个
> > > 不是仓库的协作者的话没法删除创建的issue
> 
> 我现在就删不了这个Issue

没错，结果就是删不掉

**Comment by swpfY** [comment]
你应该能删掉这个Issue（右下角）
